const { Pool } = require("pg");

const resolveAuthTable = () => {
  const candidate = process.env.AUTH_TABLE || "registration";
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(candidate) ? candidate : "registration";
};

const connectionString =
  process.env.SUPABASE_POOLER_URL ||
  process.env.SUPABASE_DATABASE_URL ||
  process.env.DATABASE_URL;

const pool = connectionString
  ? new Pool({
      connectionString,
      ssl: {
        rejectUnauthorized: false,
      },
    })
  : null;

const initPostgres = async () => {
  if (!pool) {
    // eslint-disable-next-line no-console
    console.warn("PostgreSQL URL missing. Auth routes will not work until SUPABASE_DATABASE_URL is set.");
    return;
  }

  try {
    const authTable = resolveAuthTable();

    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS ${authTable} (
        id SERIAL PRIMARY KEY,
        name VARCHAR(120) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password TEXT NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('client', 'admin')),
        is_verified BOOLEAN NOT NULL DEFAULT FALSE,
        email_verification_token TEXT,
        email_verification_expires TIMESTAMPTZ,
        password_reset_token TEXT,
        password_reset_expires TIMESTAMPTZ,
        phone VARCHAR(40) DEFAULT '',
        address TEXT DEFAULT '',
        avatar TEXT DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `;

    await pool.query(createTableQuery);

    const normalizeExistingTableQuery = `
      ALTER TABLE ${authTable}
      ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'client',
      ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS email_verification_token TEXT,
      ADD COLUMN IF NOT EXISTS email_verification_expires TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS password_reset_token TEXT,
      ADD COLUMN IF NOT EXISTS password_reset_expires TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS phone VARCHAR(40) DEFAULT '',
      ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '',
      ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT '',
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW(),
      ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
    `;

    await pool.query(normalizeExistingTableQuery);

    const fillPasswordFromLegacyQuery = `
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = current_schema()
            AND table_name = '${authTable}'
            AND column_name = 'password_hash'
        ) THEN
          EXECUTE 'UPDATE ${authTable} SET password = password_hash WHERE (password IS NULL OR password = '''') AND password_hash IS NOT NULL';
        END IF;
      END $$;
    `;

    await pool.query(fillPasswordFromLegacyQuery);

    const createIndexQuery = `
      CREATE UNIQUE INDEX IF NOT EXISTS idx_${authTable}_email ON ${authTable} (email);
    `;

    await pool.query(createIndexQuery);

    // eslint-disable-next-line no-console
    console.log("PostgreSQL initialized successfully");
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error("PostgreSQL initialization failed:", error.message);
    // eslint-disable-next-line no-console
    console.warn("Server will continue running, but auth endpoints will fail until DB is reachable.");
  }
};

module.exports = {
  pool,
  initPostgres,
};
